name: Convert to Spring Boot

on:
  workflow_dispatch:
    inputs:
      spring_boot_version:
        description: "Target Spring Boot Version"
        required: true
        type: choice
        options:
          - "3.2.12"
          - "3.3.6"
          - "3.4.2"
        default: "3.3.6"

env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false

jobs:
  migrate-java21-springboot:
    name: Migrate Java 21 + Spring Boot
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Apply OpenRewrite migration recipe
        run: |
          set -euo pipefail
          if [ -f "pom.xml" ] && [ -f ".github/rewrite/migration-recipe.yml" ]; then
            mvn -B -ntp -U org.openrewrite.maven:rewrite-maven-plugin:6.29.0:run \
              -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:3.30.0,org.openrewrite.recipe:rewrite-spring:6.30.0 \
              -Drewrite.activeRecipes=com.organization.migrations.Java21SpringBootBaseline \
              -Drewrite.configLocation=.github/rewrite/migration-recipe.yml
          else
            echo "Skipping OpenRewrite: pom.xml or centralized recipe file missing."
          fi

      - name: Build and test
        run: |
          set -euo pipefail
          if [ -f "pom.xml" ]; then
            mvn -B -ntp clean verify
          elif [ -f "gradlew" ]; then
            chmod +x gradlew
            ./gradlew --no-daemon clean test
          else
            echo "No Maven/Gradle build file found."
            exit 1
          fi

      - name: Clean generated artifacts before PR
        run: |
          set -euo pipefail
          rm -rf target .rewrite rewrite.patch

      - name: Check if migration produced commit-worthy changes
        id: changes
        run: |
          set -euo pipefail
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create Pull Request (only after successful migration/build checks)
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: migration/java21-spring-boot-${{ github.run_id }}
          delete-branch: true
          commit-message: |
            chore: migrate to Spring Boot on Java 21

            - Applied OpenRewrite recipes
            - Upgraded Java and framework dependencies
            - Passed build/tests
          title: "Convert to Spring Boot ${{ github.event.inputs.spring_boot_version }} on Java 21"
          body: |
            This PR was generated after Spring migration recipes were applied.

            Completed checks:
            - Java 21 build and tests
          labels: |
            migration
            java-21
            spring-boot
            automated
