#!/usr/bin/env bash
set -euo pipefail

ANALYSIS_JSON="$1"
TARGET_SPRING_BOOT_VERSION="${2:-3.3.6}"
TARGET_JAVA_VERSION="${3:-21}"
OUTPUT_RECIPE="${4:-.github/rewrite/migration-recipe.yml}"
CATALOG_RECIPE="${5:-templates/migration-recipe.yml}"

python3 - "$ANALYSIS_JSON" "$TARGET_SPRING_BOOT_VERSION" "$TARGET_JAVA_VERSION" "$OUTPUT_RECIPE" "$CATALOG_RECIPE" << 'PY'
import json
import sys
from pathlib import Path

analysis_path = Path(sys.argv[1])
target_boot = sys.argv[2]
target_java = int(sys.argv[3])
output_path = Path(sys.argv[4])
catalog_path = Path(sys.argv[5])

data = json.loads(analysis_path.read_text(encoding="utf-8"))
flags = data.get("flags", {})
detected_boot = str(data.get("spring_boot_version") or "").strip()

selected = []
if target_java >= 21:
    selected.append("com.organization.catalog.Java21Upgrade")
elif target_java >= 17:
    selected.append("com.organization.catalog.Java17Upgrade")
elif target_java >= 11:
    selected.append("com.organization.catalog.Java11Upgrade")

def spring_boot_dependency_recipe(version: str) -> str:
    if version.startswith("3.4"):
        return "com.organization.catalog.SpringBootDependencies_3_4"
    if version.startswith("3.2"):
        return "com.organization.catalog.SpringBootDependencies_3_2"
    if version.startswith("3.3"):
        return "com.organization.catalog.SpringBootDependencies_3_3"
    # Fallback for any 3.x not explicitly mapped.
    if version.startswith("3."):
        return "com.organization.catalog.SpringBootDependencies_3_3"
    return "com.organization.catalog.SpringBootDependencies_2_7"

if flags.get("has_spring") or flags.get("has_spring_boot"):
    if target_java >= 17:
        selected.append("com.organization.catalog.SpringBoot3Core")
        selected.append(spring_boot_dependency_recipe(target_boot))
        if flags.get("has_javax") or flags.get("has_jakarta"):
            selected.append("com.organization.catalog.JavaxToJakarta")
            selected.append("com.organization.catalog.JakartaEeModernization")
            selected.append("com.organization.catalog.JakartaAnnotationApi")
    else:
        # Avoid unnecessary Spring Boot 2.x rewrite churn (including JUnit 4->5 migration)
        # when repository is already on latest 2.7.18 for Java 11 track.
        if not detected_boot.startswith("2.7.18"):
            selected.append("com.organization.catalog.SpringBoot2Track")
        selected.append("com.organization.catalog.SpringBootDependencies_2_7")

if flags.get("has_dropwizard"):
    selected.append(
        "com.organization.catalog.DropwizardModernTrack"
        if target_java >= 17 else
        "com.organization.catalog.DropwizardJava11Track"
    )

if flags.get("has_log4j"):
    selected.append("com.organization.catalog.Log4jModernization")

selected.append("com.organization.catalog.CommonDependencyModernization")

# Deduplicate while preserving order.
selected = list(dict.fromkeys(selected))

output_path.parent.mkdir(parents=True, exist_ok=True)
composed = [
    "type: specs.openrewrite.org/v1beta/recipe",
    "name: com.organization.migrations.AutogeneratedMigration",
    "displayName: Autogenerated migration recipe",
    "description: Generated per-repository selector recipe composed from centralized catalog recipes.",
    "recipeList:",
]
for name in selected:
    composed.append(f"  - {name}")

catalog = catalog_path.read_text(encoding="utf-8").rstrip()
output = catalog + "\n---\n" + "\n".join(composed) + "\n"
output_path.write_text(output, encoding="utf-8")
PY
