#!/usr/bin/env bash
set -euo pipefail

ANALYSIS_JSON="$1"
TARGET_SPRING_BOOT_VERSION="${2:-3.3.6}"
OUTPUT_RECIPE="${3:-.github/rewrite/migration-recipe.yml}"

python3 - "$ANALYSIS_JSON" "$TARGET_SPRING_BOOT_VERSION" "$OUTPUT_RECIPE" << 'PY'
import json
import os
import sys
from pathlib import Path

analysis_path = Path(sys.argv[1])
target_boot = sys.argv[2]
output_path = Path(sys.argv[3])

data = json.loads(analysis_path.read_text(encoding="utf-8"))
flags = data.get("flags", {})

recipes = []
recipes.append("  - org.openrewrite.java.migrate.UpgradeToJava21")

if flags.get("has_spring") or flags.get("has_spring_boot"):
    # Explicitly include the recipe family requested from OpenRewrite docs.
    recipes.append("  - org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_1")
    recipes.append("  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:")
    recipes.append("      groupId: org.springframework.boot")
    recipes.append("      artifactId: spring-boot-dependencies")
    recipes.append(f"      newVersion: {target_boot}")
    recipes.append("      overrideManagedVersion: true")

if flags.get("has_javax") and not flags.get("has_jakarta"):
    recipes.append("  - org.openrewrite.java.migrate.jakarta.JavaxMigrationToJakarta")

if flags.get("has_dropwizard"):
    recipes.append("  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:")
    recipes.append("      groupId: io.dropwizard")
    recipes.append("      artifactId: dropwizard-core")
    recipes.append("      newVersion: 4.x")
    recipes.append("      overrideManagedVersion: true")

if flags.get("has_log4j"):
    recipes.append("  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:")
    recipes.append("      groupId: org.apache.logging.log4j")
    recipes.append("      artifactId: log4j-api")
    recipes.append("      newVersion: 2.25.x")
    recipes.append("      overrideManagedVersion: true")

# Keep these runtime/security-sensitive libraries aligned for modern Spring Boot + Java 21 stacks.
recipes.append("  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:")
recipes.append("      groupId: org.postgresql")
recipes.append("      artifactId: postgresql")
recipes.append("      newVersion: 42.7.x")
recipes.append("      overrideManagedVersion: true")
recipes.append("  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:")
recipes.append("      groupId: com.mysql")
recipes.append("      artifactId: mysql-connector-j")
recipes.append("      newVersion: 8.4.x")
recipes.append("      overrideManagedVersion: true")
recipes.append("  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:")
recipes.append("      groupId: org.eclipse.angus")
recipes.append("      artifactId: angus-activation")
recipes.append("      newVersion: 2.0.x")
recipes.append("      overrideManagedVersion: true")
recipes.append("  - org.openrewrite.java.dependencies.UpgradeDependencyVersion:")
recipes.append("      groupId: ch.qos.logback")
recipes.append("      artifactId: logback-classic")
recipes.append("      newVersion: 1.5.x")
recipes.append("      overrideManagedVersion: true")

output_path.parent.mkdir(parents=True, exist_ok=True)
content = [
    "type: specs.openrewrite.org/v1beta/recipe",
    "name: com.organization.migrations.AutogeneratedMigration",
    "displayName: Autogenerated migration recipe",
    "description: Generated per-repository from detected dependencies and framework versions.",
    "recipeList:",
]
content.extend(recipes)
output_path.write_text("\n".join(content) + "\n", encoding="utf-8")
PY
