#!/usr/bin/env bash
set -euo pipefail

TARGET_DIR="$1"
PROFILE="$2"
SPRING_BOOT_VERSION="$3"
CONTROL_PLANE_DIR="$4"
ANALYSIS_FILE="${5:-}"

cd "$TARGET_DIR"
echo "Starting migration for profile '$PROFILE' with target Spring Boot '$SPRING_BOOT_VERSION'"
if [[ -n "$ANALYSIS_FILE" && -f "$ANALYSIS_FILE" ]]; then
  echo "Analysis file detected: $ANALYSIS_FILE"
fi

mkdir -p .github/rewrite

if [[ -f ".github/rewrite/migration-recipe.yml" ]]; then
  echo "Using generated recipe at .github/rewrite/migration-recipe.yml"
else
  cp "$CONTROL_PLANE_DIR/templates/migration-recipe.yml" .github/rewrite/migration-recipe.yml
fi

if [[ "$PROFILE" == "spring-petclinic" ]]; then
  mkdir -p src/main/resources src/main/java/org/springframework/samples/petclinic

  # For legacy spring-petclinic, convert pom to known Boot-compatible baseline first.
  cp "$CONTROL_PLANE_DIR/templates/repo-patches/spring-petclinic/pom.xml" pom.xml
  sed -i "s/__SPRING_BOOT_VERSION__/${SPRING_BOOT_VERSION}/g" pom.xml

  if [[ ! -f "src/main/resources/application.properties" ]]; then
    cp "$CONTROL_PLANE_DIR/templates/repo-patches/spring-petclinic/src/main/resources/application.properties" src/main/resources/application.properties
  fi

  if [[ ! -f "src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java" ]]; then
    cp "$CONTROL_PLANE_DIR/templates/repo-patches/spring-petclinic/src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java" src/main/java/org/springframework/samples/petclinic/PetClinicApplication.java
  fi

  if [[ -f src/main/resources/spring/business-config.xml ]]; then
    sed -i '/persistenceUnitName/d' src/main/resources/spring/business-config.xml
    if ! grep -q 'SharedEntityManagerBean' src/main/resources/spring/business-config.xml; then
      perl -0777 -i -pe 's|(<bean id="entityManagerFactory" class="org\.springframework\.orm\.jpa\.LocalContainerEntityManagerFactoryBean"[\s\S]*?</bean>)|$1\n\n        <bean id="entityManager" class="org.springframework.orm.jpa.support.SharedEntityManagerBean"\n              p:entityManagerFactory-ref="entityManagerFactory"/>|s' src/main/resources/spring/business-config.xml
    fi
  fi
fi

rm -rf target .rewrite rewrite.patch || true

if [[ -f "pom.xml" ]]; then
  mvn -B -ntp -U org.openrewrite.maven:rewrite-maven-plugin:6.29.0:run \
    -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-migrate-java:3.27.0,org.openrewrite.recipe:rewrite-spring:6.24.0 \
    -Drewrite.activeRecipes=com.organization.migrations.AutogeneratedMigration \
    -Drewrite.configLocation=.github/rewrite/migration-recipe.yml || true
fi

if [[ "$PROFILE" == "spring-petclinic" && -f "pom.xml" ]]; then
  mvn -B -ntp clean verify \
    -Ddb.script=h2 \
    -Djpa.database=H2 \
    -Djdbc.driverClassName=org.h2.Driver \
    -Djdbc.url=jdbc:h2:mem:petclinic \
    -Djdbc.username=sa \
    -Djdbc.password=
elif [[ -f "pom.xml" ]]; then
  mvn -B -ntp clean verify
elif [[ -f "gradlew" ]]; then
  chmod +x gradlew
  ./gradlew --no-daemon clean test
else
  echo "No pom.xml or gradlew found; skipping build/test."
fi

rm -rf target .rewrite rewrite.patch || true
